version: '3.7'
services:
  backend:
    image: samvivers/backend
    container_name: backend
    depends_on:
    - database
  frontend:
    image: samvivers/frontend
    container_name: frontend
  database:
    image: mysql:5.7
    container_name: database
    environment:
    - MYSQL_ROOT_PASSWORD=groot
    - MYSQL_DATABASE=tasklist
    volumes:
    - type: volume
      source: sql
      target: /var/lib/mysql  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
    - target: 80
      published: 80
    depends_on:
    - backend
    - frontend
volumes:
  sql: